server {
    listen 80;

    # Sirve el build est?tico de React
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;  # necesario para React Router
    }

    # Proxy hacia backend Ventas (interno en K8s)
    location /api/ventas/ {
        proxy_pass http://back-ventas:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy hacia backend Despachos (interno en K8s)
    location /api/despachos/ {
        proxy_pass http://back-despachos:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
