apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: innovatech
  labels:
    app: mysql
    tier: database
spec:
  selector:
    app: mysql
  ports:
    - port: 3306         # puerto expuesto por el Service
      targetPort: 3306   # puerto interno del contenedor
  type: ClusterIP        # solo accesible dentro del cl├║ster
